Bind multiple statements
GoogleCloudPlatform/cloud-spanner-r2dbc pull request #278
Opened 2020-10-01 20:35 UTC by elefeint

This PR covers the `Statement.bind().bind().add()` flow for both SELECT and DML.

Don't review yet; I've been slacking off on unit tests and want to add them.

2020-10-06 22:44 UTC, dzou commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
> +  private boolean incompleteBinding = false;
I would rename to `startedBinding`; think this may be more clear to express the boolean

2020-10-06 22:44 UTC, dzou commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
> +    if (this.statements == null) {
Is this class meant to be re-used after a user calls `execute`? If not, I would just initialize the `this.statements` in the constructor once.

But if it is meant to be re-used, I think it may make sense to keep all the state resetting logic inside `execute()` just to keep in once place. `execute()` can be the method which runs the statements and then clears the list.

2020-10-06 22:44 UTC, dzou commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatement.java
> +    return Flux.fromIterable(statements).flatMapSequential(statement ->
Not 100% sure on this; but I think you can just delegate a call to `executeSingle(...)` via:

`return Flux.fromIterable(statements).flatMapSequential(statement -> executeSingle(statement));`

2020-10-07 13:52 UTC, ttomsu commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
> +  private boolean incompleteBinding = false;
Is the goal to make this multi-threaded safe? Because I don't know if this state variable would survive well in a race condition.

2020-10-07 13:52 UTC, ttomsu commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java
> +  1) exercises s a different internal code path than selectMultipleBoundParameterSetsNoTransaction()
stray 's'

2020-10-07 16:50 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
> +  private boolean incompleteBinding = false;
For Connection, the spec explicitly says that "connection object can be shared across multiple threads that serially run operations by using appropriate synchronization mechanisms" -- so it's expected to be externally synchronized and does not need to take care of simultaneously modified state. For Statement, there is no explicit clause like that, but looking at the reference H2 implementation, the same assumption is made: https://github.com/r2dbc/r2dbc-h2/blob/main/src/main/java/io/r2dbc/h2/H2Statement.java

2020-10-07 17:12 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
> +    if (this.statements == null) {
The spec says "Parameterized statements may be cached by R2DBC implementations for reuse (for example, for prepared statement execution).", so it's left up to implementation. I would prefer to at least not preclude reuse of a `Statement`, even if we don't explicitly support it.

Which state resetting do you mean? The typical flow is:
```
conn.createStatement(statement)
                    .bind("uuid", uuid1).bind("title", "A").add()
                    .bind("uuid", uuid2).bind("title", "B").add()
                    .bind("uuid", uuid3).bind("title", "C").add()
                    .execute()
```

So the in-progress binding needs to be reset after each `add()` (so, theoretically, could be done in `bind()` with some logic), but it's not enough to reset it in `execute()`.

Unless you meant that bound variables should be removed after `execute()`? I don't think so -- if we are going to allow reuse, the value is in keeping the statement with the parameters bound. Creating a new Statement is a simple one liner, but binding variables could be involved.

2020-10-07 17:15 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryStatement.java
> +    return Flux.fromIterable(statements).flatMapSequential(statement ->
Good catch, thanks!

2020-10-07 17:16 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java
> +  1) exercises s a different internal code path than selectMultipleBoundParameterSetsNoTransaction()
I am just going to blame the cat.

2020-10-07 17:30 UTC, dzou commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
> +    if (this.statements == null) {
Ah I see, that makes sense.

What I meant with the state-clearing was that `execute()` would need to clear the statements list I think if you want to re-use it (either set to null or `.clear()`), but I don't think this is being done yet.

I think it might be simpler to just do `this.statements = new ArrayList<>();` in the constructor, and then do a `this.statements.clear()` in the `execute()` method after running; then you can remove all the null-checks I believe.

2020-10-07 18:21 UTC, dzou submitted a review, later dismissed

2020-10-07 18:56 UTC, meltsufin approved these changes
Just one optional suggestion. Otherwise looks good to merge!

2020-10-07 18:56 UTC, meltsufin commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
> +    if (this.statements != null) {
Like Dan suggested, it might be easier to just make sure that `this.statements` is never `null`.
You can even re-use it for single statements where you would check for `size() == 0`.

2020-10-07 19:30 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
> +    if (this.statements != null) {
Right, I was trying to avoid creating a list by default because the most common scenario is to have a string query with only a single set of bound parameters. Since statement execution is the most common operation for a database, it may make sense to save on an extra object per statement.

2020-10-07 19:44 UTC, meltsufin commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/AbstractSpannerClientLibraryStatement.java
> +    if (this.statements != null) {
OK, I see.

2020-10-08 14:29 UTC, dmitry-s requested changes

2020-10-08 14:29 UTC, dmitry-s commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
> +   * <p>If no transaction is active, a single-use transaction will be used.
```suggestion
   * Allows running DML statements in a batch.
   * <p>
   * If no transaction is active, a single-use transaction will be used.
```

2020-10-08 14:29 UTC, dmitry-s commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatement.java
> +
```suggestion
```

2020-10-08 14:49 UTC, meltsufin approved these changes

2020-10-09 02:05 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
> +   * <p>If no transaction is active, a single-use transaction will be used.
google checkstyle is yelling at me now -- "tag should be placed immediately before the first word, with no space after." :(

2020-10-09 17:55 UTC, meltsufin approved these changes

2020-10-09 18:04 UTC, merged