Customize project ID, user-agent string from configuration
GoogleCloudPlatform/cloud-spanner-r2dbc pull request #280
Opened 2020-10-13 19:53 UTC by elefeint

`DatabaseClientReactiveAdapter` was already passing the configured project ID when creating `SpannerClient`. The project ID set in `SpannerOptions` is technically unused, but it seems worth explicitly setting it to the same value, so we don't have to wonder what value it is.

This PR also, since it's in the same configuration code:
* reintroduces User-Agent string for V2 (it was in a gRPC-specific implementation class in V1).
* propagates credentials. This required a small refactoring -- previously the code assumed GoogleCredentials, which precluded testing with NoCredentials.

Fixes #257.

2020-10-13 20:01 UTC, dzou submitted a review, later dismissed
So `OAuthCredentials` is the correct class to be passing around over `GoogleCredentials`?

2020-10-13 20:17 UTC, meltsufin requested changes

2020-10-13 20:17 UTC, meltsufin commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactoryTest.java
> +    assertThat(options.getUserAgent()).startsWith("cloud-spanner-r2dbc/");
If you want to make the test a bit more robust, feel free to get inspiration from Spring Cloud GCP. :)
```java
	UserAgentHeaderProvider subject = new UserAgentHeaderProvider(this.getClass());

		String versionRegex = "\\d+\\.\\d+\\.\\d+\\.[BUILD-SNAPSHOT|M\\d+|RC\\d+|RELEASE]$";
		assertThat(subject.getHeaders()).containsKey("User-Agent");
		assertThat(subject.getHeaders().get("User-Agent")).matches(
				Pattern.compile("Spring/" + versionRegex + " spring-cloud-gcp-core/" + versionRegex));
		assertThat(subject.getHeaders().size()).isEqualTo(1);
```

2020-10-14 15:14 UTC, ttomsu submitted a review, later dismissed

2020-10-14 19:07 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnectionFactoryTest.java
> +    assertThat(options.getUserAgent()).startsWith("cloud-spanner-r2dbc/");
Since the driver only has one Maven module, I'm going to stick with the basic UAString test. (for posterity -- based on the experience of spring-cloud/spring-cloud-gcp#2556, we've learned that in order for package information to be available even in maven's verify phase, the package retrieval needs to be in a different JAR from the one tests are being run in).

2020-10-14 19:08 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnectionConfiguration.java
> +  public static final String USER_AGENT_KEY = "User-Agent";
yep.

2020-10-14 19:56 UTC, elefeint commented
@dzou Yes, `GoogleCredentials` extend from `OAuth2Credentials`, and also `NoCredentials` extends from the same.

2020-10-14 21:02 UTC, dzou approved these changes

2020-10-15 01:28 UTC, meltsufin approved these changes

2020-10-15 02:00 UTC, merged