V2  row metadata
GoogleCloudPlatform/cloud-spanner-r2dbc pull request #281
Opened 2020-10-13 21:57 UTC by dmitry-s

2020-10-13 22:23 UTC, elefeint requested changes
Looks good; just minor stuff.

2020-10-13 22:23 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRow.java
> +    return new SpannerClientLibraryRowMetadata(this.rowFields.getType().getStructFields());
Add a null check for `rowFields`. Can type be null? Probably not if it's a proto, right?

2020-10-13 22:23 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRowMetadata.java
> +   * Mapping of column names to its integer index position in the row.
nit: s/names/name or make the rest plural.

2020-10-13 22:23 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRowMetadata.java
> +    this.columnNameIndex = new HashMap<>();
Can just do it inline with declaration.

2020-10-13 22:23 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRowMetadata.java
> +    return Collections.unmodifiableList(this.columnMetadatas);
No need for wrapping it in unmodifiable list here since the class field is already unmodifiable.

2020-10-13 22:23 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java
> +    List<ColumnMetadata> columnMetadataList = Arrays
Consider naming it `expectedColumnMetadataList`; less of a mental jump to know there is no logic to check here.

2020-10-13 22:23 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java
> +        .expectNext(columnMetadataList)
I think if you use `expectNextMatches()` here, it won't be necessary to create a custom list to satisfy equality with unmodifiable list -- you'll be able to use AssertJ fluent list operators to verify inside the predicate.

2020-10-14 21:51 UTC, dmitry-s commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryRow.java
> +    return new SpannerClientLibraryRowMetadata(this.rowFields.getType().getStructFields());
It's unlikely, but I'll add a check.

2020-10-14 22:05 UTC, dmitry-s commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/ClientLibraryBasedIT.java
> +        .expectNext(columnMetadataList)
Didn't work for `Iterable`, not sure why

2020-10-15 02:02 UTC, elefeint approved these changes

2020-10-15 11:29 UTC, merged