Add support for a connection healthcheck
GoogleCloudPlatform/cloud-spanner-r2dbc pull request #283
Opened 2020-10-19 17:35 UTC by dzou

This adds support for a Spanner connection health check.

Fixes #274 .

2020-10-20 21:06 UTC, dmitry-s commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryConnection.java
> +          "Local validation health checks is not supported for Cloud Spanner.");
```suggestion
          "Local validation health checks are not supported for Cloud Spanner.");
```

2020-10-21 13:32 UTC, elefeint requested changes
Sorry for the delay!

Looks good, but we used to support local health check, and a part of your full healthcheck lends itself to becoming local.

This also led me into a rabbit hole, at the end of which was realizing we are not cleaning up client library-created sessions.

2020-10-21 13:32 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
> +      if (executorService.isShutdown()) {
This seems like a good candidate for `ValidationDepth.LOCAL`.

I was thinking another useful local check would require saving `Spanner spannerClient` from the constructor, and calling `spannerClient.isClosed()`, but then realized we are not actually closing it, so I filed to track addressing the session leaking in #284.

2020-10-21 13:32 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
> +  @Override
You might be able to just remove this override completely -- the `TestKit` parent should run as is.

2020-10-21 18:30 UTC, dzou commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
> +      if (executorService.isShutdown()) {
Done.

2020-10-21 18:32 UTC, dzou commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
> +  @Override
Done.

2020-10-21 18:55 UTC, elefeint approved these changes
Thanks!

2020-10-21 19:45 UTC, merged