support Long to Integer conversion on read
GoogleCloudPlatform/cloud-spanner-r2dbc pull request #286
Opened 2020-11-03 01:31 UTC by dmitry-s

fixes #276

2020-11-03 16:50 UTC, elefeint requested changes
I like the `SpannerClientLibrariesConverter` abstraction. Great tests, too.

You may be able to remove a test override `SpannerClientLibraryTestKit.transactionCommit()`, and its helper `extractColumnsLong()`.

2020-11-03 16:50 UTC, elefeint commented on cloud-spanner-r2dbc/pom.xml
> +          <source>11</source>
Java 8 came from these properties below, which I think are read by the same plugin, so it's easier to change them there:
```    
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
```

2020-11-03 16:50 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibrariesConverters.java
> +  private static ArrayList<SpannerClientLibrariesConverter<?>> createConverters() {
Return generic `List`?

2020-11-03 16:50 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoder.java
> +    return SpannerClientLibrariesConverters.convert(value, type);
Having it be a static method makes it not that easy to unit test separately from the specific converter logic. What do you think about making `SpannerClientLibrariesConverters` have state?

2020-11-03 16:50 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoderTest.java
> +            new long[]{123456L, 45678L},
Checkstyle made you do this?! Sounds unlike the usual style.

2020-11-03 20:57 UTC, dmitry-s commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoderTest.java
> +            new long[]{123456L, 45678L},
GoogleStyle plugin did that.

2020-11-03 21:16 UTC, elefeint reviewed
It may be easier to reason about PRs if the JDK changes are in their own tiny standalone one.

2020-11-03 21:16 UTC, elefeint commented on cloud-spanner-r2dbc/pom.xml
> +          <source>11</source>
Also, .travis.yml needs to change to run on the newer JDK - - right now, the build fails with `Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project cloud-spanner-r2dbc: Fatal error compiling: invalid target release: 11 -> [Help 1]`

2020-11-03 22:17 UTC, dmitry-s commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoder.java
> +    return SpannerClientLibrariesConverters.convert(value, type);
How about we keep it like this for now and if/when we need we'll switch to stateful `SpannerClientLibrariesConverters`?

2020-11-03 22:31 UTC, meltsufin reviewed
I think there are opportunities here to improve the conversion design.
However, if you think that would be better done in a separate PR, that's fine too.

2020-11-03 22:31 UTC, meltsufin commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibrariesConverters.java
> +public class SpannerClientLibrariesConverters {
Javadoc? The name sounds odd. Did you mean `SpannerClientLibraryConverters`?
Also, instead of making it a collection of `static` methods, why not just make it the converter?

2020-11-03 22:31 UTC, meltsufin commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoder.java
> +    return SpannerClientLibrariesConverters.convert(value, type);
Can you have an interface and implementation that has a single method `T convert(Struct struct, int index, Class<T> type)`? Then all of these conversion supporting decoders can move in there. I think it would be much easier to test conversion logic that way.

2020-11-06 14:18 UTC, elefeint approved these changes
Let's get it in; we can always decide on a refactoring later.

2020-11-09 18:57 UTC, meltsufin commented
@dmitry-s Do you want to merge this in?

2020-11-09 18:58 UTC, meltsufin approved these changes

2020-11-10 00:46 UTC, merged