Add Autocommit Support
GoogleCloudPlatform/cloud-spanner-r2dbc pull request #289
Opened 2020-11-12 20:47 UTC by dzou

Implements the `autoCommit` setting for the connection.

Fixes https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/issues/275

Reference: https://github.com/r2dbc/r2dbc-spi/blob/main/r2dbc-spec/src/main/asciidoc/transactions.adoc#auto-commit-mode

2020-11-12 21:18 UTC, elefeint requested changes
Looks great, just a couple of minor comments.

2020-11-12 21:18 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
> +        result = Mono.from(this.commitTransaction());
Just make `commitTransaction()` return a `Mono`. It was an oversight on my part to return plain publishers.

2020-11-12 21:18 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
>    public void changeAutoCommitCommitsTransaction() {
You may be able to remove this override completely, since @dmitry-s added the Long-to-Integer conversion.

2020-11-12 21:18 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
>    public void sameAutoCommitLeavesTransactionUnchanged() {
I think you can completely remove this override.

2020-11-12 21:18 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java
> +    this.executorService = Executors.newFixedThreadPool(1);
Sounds like `.newSingleThreadExecutor`, but feel free to leave it as is if it's easier to change number of threads in the future.

2020-11-12 21:18 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java
> +    this.executorService.shutdownNow();
Okay, I really should do this too in the test I added in last PR...

2020-11-12 21:18 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java
> +  public void testChangeAutocommit() {
`testChangeAutocommitCommitsCurrentTransaction`?

2020-11-13 17:21 UTC, dzou commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
>    public void changeAutoCommitCommitsTransaction() {
Hmm doesn't seem to quite work. I get this error:

```
java.lang.AssertionError: expectation "autoCommit(true) committed the transaction. Expecting a value to be present" failed (expected value: 200; actual value: 200)
```

2020-11-13 17:22 UTC, dzou commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
> +        result = Mono.from(this.commitTransaction());
Done.

2020-11-13 17:22 UTC, dzou commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
>    public void sameAutoCommitLeavesTransactionUnchanged() {
Done.

2020-11-13 17:23 UTC, dzou commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java
> +    this.executorService = Executors.newFixedThreadPool(1);
Done.

2020-11-13 17:23 UTC, dzou commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java
> +    this.executorService.shutdownNow();
Hehe :)

2020-11-13 17:23 UTC, dzou commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapterTest.java
> +  public void testChangeAutocommit() {
Done.

2020-11-13 17:26 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
>    public void changeAutoCommitCommitsTransaction() {
Rebase from master -- you need #286.

2020-11-13 17:28 UTC, dzou commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
> +  DatabaseClientReactiveAdapter(
Hmm I wasn't quite sure how to do this because `this()` must be called on first line, however the txnManager needs to re-use the reference to `dbClient` and `executorService`.

Tried something like this but was not possible:

```
  public DatabaseClientReactiveAdapter(
      Spanner spannerClient,
      SpannerConnectionConfiguration config) {

    DatabaseClient dbClient =
        spannerClient.getDatabaseClient(
            DatabaseId.of(config.getProjectId(), config.getInstanceName(), config.getDatabaseName()));
    
    ExecutorService executorService =
        Executors.newFixedThreadPool(config.getThreadPoolSize());
    
    this(
        spannerClient,
        dbClient,
        spannerClient.getDatabaseAdminClient(),
        executorService,
        config,
        new DatabaseClientTransactionManager(dbClient, executorService)
    );
  }
```

But I only added that constructor to pass in mockito mocks into for unit tests. Maybe it's ok to leave as is?

2020-11-13 17:31 UTC, dzou commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
>    public void changeAutoCommitCommitsTransaction() {
Yup I have that change in my branch, see my branch history:

![image](https://user-images.githubusercontent.com/3209274/99102451-157c4380-25ac-11eb-88ed-05db95f8c3a6.png)

2020-11-13 17:51 UTC, elefeint approved these changes

2020-11-13 17:51 UTC, elefeint commented on cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/DatabaseClientReactiveAdapter.java
> +  DatabaseClientReactiveAdapter(
Yeah, that's fine.

2020-11-13 17:51 UTC, elefeint commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
>    public void changeAutoCommitCommitsTransaction() {
Weird! Let's merge it and I'll see what that test wants.

2020-11-13 17:52 UTC, dzou commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/it/SpannerClientLibraryTestKit.java
>    public void changeAutoCommitCommitsTransaction() {
Hmm from what it looks like the underlying TCK test never does a cast to `Integer`:

```
  @Test
  default void changeAutoCommitCommitsTransaction() {
    ((FirstStep)Mono.from(this.getConnectionFactory().create()).flatMapMany((connection) -> {
      return Flux.from(connection.setAutoCommit(false)).thenMany(connection.beginTransaction()).thenMany(connection.createStatement(this.expand(TestKit.TestStatement.INSERT_VALUE200)).execute()).flatMap(Result::getRowsUpdated).thenMany(connection.setAutoCommit(true)).thenMany(connection.createStatement(this.expand(TestKit.TestStatement.SELECT_VALUE)).execute()).flatMap((it) -> {
        return it.map((row, metadata) -> {
          return this.extractColumn(row);
        });
      }).concatWith(close(connection));
    }).as(StepVerifier::create)).expectNext(200).as("autoCommit(true) committed the transaction. Expecting a value to be present").verifyComplete();
  }
```

But this is different than the decoder test which does a `row.get(1, Integer.class)`; I feel like this may be the difference

2020-11-13 18:00 UTC, merged