Adding Spanner JSON Type support
GoogleCloudPlatform/cloud-spanner-r2dbc pull request #456
Opened 2021-11-08 18:16 UTC by zhumin8

Adding Spanner JSON Type support
JSON support is present in Client library since [6.12.0 release](https://github.com/googleapis/java-spanner/pull/1364).
This PR intend to add JSON support to our repo. 
Note that ARRAY<JSON> support is not included and is intended as a follow-up PR to this.

The major changes include:
- Add a `JsonWrapper` class.
- Add binder and decoder.
- Add String to JsonWrapper for read.
- Add to r2dbc sample and spring data r2dbc sample
- README docs
- register `JsonWrapper.class` as simple type in spring data dialect.

**Putting this PR in draft state as I am still missing at least one integration test for spring data dialect.**

I've been summarizing my understanding and thoughts in this [doc](https://docs.google.com/document/d/1cUwK6Q9blkPAPwe-pEQPZew6WUW4RXrOM-B78YTDu8w/edit?resourcekey=0-uwAk32loGgKqLtrrJwaenw#bookmark=id.w6knjqj8zn). Feel free to comment as you review this. I will remove this link later before merging in.

2021-11-10 16:01 UTC, elefeint requested changes
Very nice! 
I wonder if we can make life even easier for end users on some of configuration, but it's already a huge help.

2021-11-10 18:27 UTC, zhumin8 commented on cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/src/main/java/com/example/BookExampleApp.java
> +        .add();
Oh, thanks for the link. wasn't aware of this.

2021-11-10 18:27 UTC, zhumin8 commented on cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/WebController.java
> +          produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
Good catch! yes, this is redundant.

2021-11-10 18:30 UTC, zhumin8 commented on cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/WebController.java
> +            .select(Book.class)
Hmm, I missed that we already have `BookRepository` autowired in.
Though with spanner, I cannot use `deleteAll()` directly as it result in "INVALID_ARGUMENT: DELETE must have a WHERE clause" error. So the line still look pretty similar.

2021-11-10 20:54 UTC, zhumin8 commented on cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/WebController.java
> +  static class PostBody {
I added this intermediary `PostBody` because `Book` had multiple constructors and I did not find simpler way deal with it. But on a second look, this could totally be simplified with only one constructor in `Book`. Pushing an update soon.

2021-11-10 22:08 UTC, elefeint commented on cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/WebController.java
> +            .select(Book.class)
Oh! File it as a bug against us. There should be a way fix this with the dialect.
It's true that Spanner requires a condition for deletes.

2021-11-10 22:55 UTC, zhumin8 commented on cloud-spanner-r2dbc/src/test/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryDecoderTest.java
> +
I am on the borderline here. On one hand, I feel that parameterized tests are a little overkill for 2 set of params, and adds burden when reading; On the other hand, there are already parameterized tests setup in this test that are parallel to this added one, and I feel it's easier to read when the tests logic are parallel and easier to identify differences between tests .

2021-11-11 19:17 UTC, zhumin8 commented on cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialect.java
> +  public Collection<? extends Class<?>> getSimpleTypes() {
I am not registering any custom converters for the dialect as of now. Will override this when adding the map converter in.

2021-11-11 19:17 UTC, zhumin8 commented on cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/JsonToMapConverter.java
> +public class JsonToMapConverter implements Converter<JsonWrapper, Map<String, Object>> {
I can move this converter to the dialect and free our user for setting up for Maps. Will add a couple of tests and update this.

2021-11-12 22:13 UTC, zhumin8 commented
Got a few more changes to make to tests. Will request review again when I am done.

2021-11-15 20:19 UTC, zhumin8 commented on cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/JsonToMapConverter.java
> +  public Map<K, V> convert(JsonWrapper json) throws JsonParseException {
Let `JsonParseException` surface if gson deserialization is not successful.

2021-11-15 20:22 UTC, zhumin8 commented on cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/MapToJsonConverter.java
> +    return JsonWrapper.of(this.gson.toJson(source));
this simple form `gson.toJson()` does not throw exception.

2021-11-17 15:47 UTC, elefeint approved these changes
LGTM -- great work!

2021-11-17 15:47 UTC, elefeint commented on README.md
> +If using Spring Data, default converters to/from `Map` are ready to use out-of-box for key,  value type of `String`, `Boolean` and `Double`. Custom converters can be used to allow Json conversion dir
```suggestion
If using Spring Data, default converters to/from `Map` are ready to use out-of-box for key or value type of `String`, `Boolean` and `Double`. Custom converters can be used to allow Json conversion directly to/from collections or user-defined types. Examples of using `Map` and custom class `Review` for Json field are provided in the [Spring Data sample application](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/tree/main/cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample)
```

2021-11-17 15:47 UTC, elefeint commented on cloud-spanner-spring-data-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/springdata/SpannerR2dbcDialect.java
> +    return Arrays.asList(new JsonToMapConverter(this.gson), new MapToJsonConverter(this.gson));
```suggestion
    return Arrays.asList(new JsonToMapConverter<>(this.gson), new MapToJsonConverter<>(this.gson));
```

This will explicitly set parameterized types to `<Object, Object>`.

2021-11-17 18:13 UTC, zhumin8 commented on cloud-spanner-r2dbc-samples/cloud-spanner-spring-data-r2dbc-sample/src/main/java/com/example/CustomConfiguration.java
> +  public class JsonToReviewsConverter implements Converter<JsonWrapper, Review> {
A note for future to revisit: This could be a useful feature to add!

2021-11-17 18:45 UTC, merged